# Generated by Django 4.1 on 2023-04-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionbuilder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='css',
        ),
        migrations.RemoveField(
            model_name='page',
            name='html',
        ),
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.JSONField(default='default'),
        ),
    ]
