# Generated by Django 4.1 on 2023-04-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionbuilder', '0002_remove_page_css_remove_page_html_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
