# Generated by Django 4.1 on 2023-04-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionbuilder', '0003_page_public_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='css',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='page',
            name='html',
            field=models.TextField(default=''),
        ),
    ]
